apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app
    
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:                         #better practice is using secrets
        - name: POSTGRES_USER      #but for example we use env:
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"